### ISSUE TITLE
creating new-module

### ISSUE THREAD

**Issue by runa988** [shakir01/LiFi-WiFi-Hybrid-System-in-ns3#1]
arun@arunVB:~/ns-allinone-3.33/ns-3.33/src$ ./utils/create-module.py HLWNets
bash: ./utils/create-module.py: No such file or directory

I am getting this error while creating a new module in src. please provide a solution to proceed further

**Comment by shakir01** [comment]
I have uploaded all the files, kindly check it again

**Comment by runa988** [comment]
arun@arun:~/ns3/ns-3.31$ ./waf build
Waf: Entering directory `/home/arun/ns3/ns-3.31/build'
Could not find a task generator for the name 'ns3-LiFi'
arun@arun:~/ns3/ns-3.31$ 

hi sir, i am getting this error message, while creating the module. kindly help me out to resolve my problem.

**Comment by runa988** [comment]
arun@arun:~/ns3/ns-3.31$ ./waf build
Waf: Entering directory `/home/arun/ns3/ns-3.31/build'
Could not find a task generator for the name 'ns3-LiFi'
arun@arun:~/ns3/ns-3.31$ 

Hi sir, i am getting above error, while i am creating new module (LiFi) in src. kindly help me out to resolve the above mention issue.

**Comment by runa988** [comment]
I created all the step from 1 to 6. where i am getting error at step-7 as mention below after 
./waf configure --enable-examples --enable-tests

arun@arun:/ns3/ns-3.31$ ./waf build
Waf: Entering directory `/home/arun/ns3/ns-3.31/build'
Could not find a task generator for the name 'ns3-LiFi'
arun@arun:/ns3/ns-3.31$


Hi sir, i am getting above error, while i am creating new module (LiFi) in src. kindly help me out to resolve the above mention issue.
@runa988

**Comment by runa988** [comment]
Dear sir, 
i getting the follow error while, i am creating "lifi" module in src.
i followed all the step 1 to 6 as mention in the documentation. while i am doing 
./waf build
i getting this sort for error.

configure' finished successfully (2.883s)
arun@arun:~/ns3/ns-3.31$ ./waf build
Waf: Entering directory `/home/arun/ns3/ns-3.31/build'
Waf: Leaving directory `/home/arun/ns3/ns-3.31/build'
source not found: 'model/lifi-propagation-loss-model.cc' in bld(source=['model/lifi-propagation-loss-model.cc', 'model/lifi-snr.cc', 'model/lifi-phy.cc', 'model/lifi-mobility-model.cc', 'model/lifi-error-model.cc', 'model/lifi-channel.cc', 'model/lifi-net-device.cc', 'model/lifi-tx-net-device.cc', 'model/lifi-rx-net-device.cc', 'model/lifi-mac-low.cc', 'model/lifi-ap-mac.cc', 'model/lifi-sta-mac.cc', 'model/lifi-tx-mac.cc', 'model/lifi-rx-mac.cc', 'model/lifi-mac-queue.cc', 'model/lifi-user-device-infos.cc', 'model/beacon-response-tag.cc', 'model/lifi-application.cc', 'model/lifi-regular-mac.cc', 'model/PerformanceAnalysis.cc', 'model/lifi-capability-information.cc', 'model/mac-resources-tag.cc', 'model/remote-station-manager.cc', 'helper/lifi-helper.cc', 'helper/wifi-ap-helper.cc', 'helper/lifi-phy-helper.cc', 'helper/lifi-mac-helper.cc', 'model/wifi-ap-net-device.cc', 'model/lifi-random-waypoint-mobility-model.cc', 'model/lifi-constant-velocity-mobility-model.cc', 'model/received-data-model.cc', 'model/my-tag.cc'], target='../../lib/ns3.31-lifi-debug', meths=['_add_test_code', 'apply_bundle', 'process_rule', 'process_source', 'apply_link', 'apply_implib', 'install_boost', 'process_use', 'collect_compilation_db_tasks', 'propagate_uselib_vars', 'apply_incpaths', 'apply_vnum', 'set_macosx_deployment_target'], features=['cxx', 'cxxshlib', 'ns3module'], path=/home/arun/ns3/ns-3.31/src/lifi, idx=1, tg_idx_count=155, is_static=False, vnum=None, module_deps=['internet', 'mobility'], install_path='${LIBDIR}', _name='ns3-lifi', dependencies=['internet', 'mobility'], uselib='', use=['ns3-internet', 'ns3-mobility'], test=False, is_ns3_module=True, ns3_dir_location='src/lifi', pcfilegen=bld(source=[], target='', meths=[], features='ns3pcfile', path=/home/arun/ns3/ns-3.31/src/lifi, idx=2, tg_idx_count=156, module='ns3-lifi', _name='') in /home/arun/ns3/ns-3.31/src/lifi, posted=True) in /home/arun/ns3/ns-3.31/src/lifi

Kindly helpme out to resolve the above issue.

**Comment by runa988** [comment]
hello sir
kindly help me to resolve the above-mentioned problem at the earliest.

**Comment by shakir01** [comment]
> hello sir
> kindly help me to resolve the above-mentioned problem at the earliest.

what ubuntu version you are trying I tried it again and it is working for me

**Comment by runa988** [comment]
DEAR Sir,
 I am using Ubuntu 20.4.2 LTS

**Comment by runa988** [comment]
Sir,
In src/lifi/wscript, the below-following .cc and .h files are not present in your doc.
 these files are not present in the model folder. that you provided in a git repository.
    1)         model/lifi-propagation-loss-model.cc',
    2)         'model/lifi-snr.cc',
    3)         'model/lifi-phy.cc',
    4)         'model/lifi-mobility-model.cc', 
    5)         'model/lifi-error-model.cc',
    6)         'model/lifi-channel.cc',
    7)         'model/lifi-net-device.cc',
    8)         'model/lifi-tx-net-device.cc',
    9)         'model/lifi-rx-net-device.cc',
    10)         'model/lifi-mac-low.cc',
    11)         'model/lifi-sta-mac.cc',
    12)         'model/lifi-tx-mac.cc',
    13)         'model/lifi-rx-mac.cc',
    14)         'model/lifi-mac-queue.cc',
    15)         'model/lifi-user-device-infos.cc',
    16)         'model/lifi-application.cc',
    17)         'model/lifi-regular-mac.cc',
    18)         'model/lifi-capability-information.cc',
    19)         'model/mac-resources-tag.cc',
    20)         'model/remote-station-manager.cc',
    21)         'model/wifi-ap-net-device.cc',
    22)         'model/my-tag.cc',
    
Respective header files for above .cc files.


 1)         'model/lifi-snr.h',
    2)         'model/lifi-propagation-loss-model.h',
    3)         'model/lifi-mobility-model.h', 
    4)         'model/lifi-error-model.h',
    5)         'model/lifi-channel.h',
    6)         model/lifi-phy.h',
    7)         'model/lifi-sta-mac.h',
    8)         'model/lifi-tx-mac.h',
    9)         'model/lifi-rx-mac.h',
    10)         'model/lifi-net-device.h',
    11)         'model/lifi-tx-net-device.h',
    12)         'model/lifi-rx-net-device.h',
    13)         'model/lifi-mac-low.h',
    14)         'model/lifi-mac-queue.h',
    15)         'model/lifi-user-device-infos.h',
    16)         'model/lifi-regular-mac.h',
    17)         'model/lifi-application.h', 
    18)         'model/lifi-capability-information.h',
    19)         'model/mac-resources-tag.h',
    20)         'model/beacon-response-tag.h',
    21)         'model/remote-station-manager.h',
    22)         'model/commons.h',
    23)         'model/lifi-random-waypoint-mobility-model.h',
    24)         'model/lifi-constant-velocity-mobility-model.h',
    25)         'model/received-data-model.h',
    26)         'model/my-tag.h'

sir, kindly upload those docs, so it will be helpful to complete the task.

**Comment by shakir01** [comment]
> Sir,
> In src/lifi/wscript, the below-following .cc and .h files are not present in your doc.
> these files are not present in the model folder. that you provided in a git repository.
> 1) model/lifi-propagation-loss-model.cc',
> 2) 'model/lifi-snr.cc',
> 3) 'model/lifi-phy.cc',
> 4) 'model/lifi-mobility-model.cc',
> 5) 'model/lifi-error-model.cc',
> 6) 'model/lifi-channel.cc',
> 7) 'model/lifi-net-device.cc',
> 8) 'model/lifi-tx-net-device.cc',
> 9) 'model/lifi-rx-net-device.cc',
> 10) 'model/lifi-mac-low.cc',
> 11) 'model/lifi-sta-mac.cc',
> 12) 'model/lifi-tx-mac.cc',
> 13) 'model/lifi-rx-mac.cc',
> 14) 'model/lifi-mac-queue.cc',
> 15) 'model/lifi-user-device-infos.cc',
> 16) 'model/lifi-application.cc',
> 17) 'model/lifi-regular-mac.cc',
> 18) 'model/lifi-capability-information.cc',
> 19) 'model/mac-resources-tag.cc',
> 20) 'model/remote-station-manager.cc',
> 21) 'model/wifi-ap-net-device.cc',
> 22) 'model/my-tag.cc',
> 
> Respective header files for above .cc files.
> 
> 1. ```
>        'model/lifi-snr.h',
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    
>    1. ```
>           'model/lifi-propagation-loss-model.h',
>       ```
>    2. ```
>           'model/lifi-mobility-model.h', 
>       ```
>    3. ```
>           'model/lifi-error-model.h',
>       ```
>    4. ```
>           'model/lifi-channel.h',
>       ```
>    5. ```
>           model/lifi-phy.h',
>       ```
>    6. ```
>           'model/lifi-sta-mac.h',
>       ```
>    7. ```
>           'model/lifi-tx-mac.h',
>       ```
>    8. ```
>           'model/lifi-rx-mac.h',
>       ```
>    9. ```
>           'model/lifi-net-device.h',
>       ```
>    10. ```
>            'model/lifi-tx-net-device.h',
>        ```
>    11. ```
>            'model/lifi-rx-net-device.h',
>        ```
>    12. ```
>            'model/lifi-mac-low.h',
>        ```
>    13. ```
>            'model/lifi-mac-queue.h',
>        ```
>    14. ```
>            'model/lifi-user-device-infos.h',
>        ```
>    15. ```
>            'model/lifi-regular-mac.h',
>        ```
>    16. ```
>            'model/lifi-application.h', 
>        ```
>    17. ```
>            'model/lifi-capability-information.h',
>        ```
>    18. ```
>            'model/mac-resources-tag.h',
>        ```
>    19. ```
>            'model/beacon-response-tag.h',
>        ```
>    20. ```
>            'model/remote-station-manager.h',
>        ```
>    21. ```
>            'model/commons.h',
>        ```
>    22. ```
>            'model/lifi-random-waypoint-mobility-model.h',
>        ```
>    23. ```
>            'model/lifi-constant-velocity-mobility-model.h',
>        ```
>    24. ```
>            'model/received-data-model.h',
>        ```
>    25. ```
>            'model/my-tag.h'
>        ```
> 
> sir, kindly upload those docs, so it will be helpful to complete the task.

You are right some of the files are missing.
I have uploaded all the files now. Please check again. And if you have any issues please do not hesitate to inform me.
Regards

**Comment by runa988** [comment]
Dear Sir,
Thank you. I will redo the things and let you know the status.

**Comment by runa988** [comment]
Dear sir,
now i getting this following errors, kindly help-me to resolve

configure' finished successfully (4.449s)
 =>  /usr/bin/python3 waf build
Waf: Entering directory `/home/arun/ns-allinone-3.31/ns-3.31/build'
[1904/2121] Compiling src/lifi/model/wifi-ap-net-device.cc
[1905/2121] Compiling src/lifi/model/lifi-constant-velocity-mobility-model.cc
[1906/2121] Compiling src/lifi/model/lifi-user-device-infos.cc
[1907/2121] Compiling src/lifi/model/received-data-model.cc
[2047/2121] Compiling src/lifi/model/lifi-mac-low.cc
[2048/2121] Compiling src/lifi/model/mac-resources-tag.cc
[2049/2121] Compiling src/lifi/model/lifi-regular-mac.cc
[2050/2121] Compiling src/lifi/helper/wifi-ap-helper.cc
In file included from ./ns3/tdma-controller.h:38,
                 from ./ns3/tdma-mac.h:33,
                 from ../src/lifi/model/lifi-user-device-infos.h:5,
                 from ../src/lifi/model/lifi-user-device-infos.cc:1:
./ns3/simple-wireless-channel.h:68:20: error: conflicting return type specified for ‘virtual uint32_t ns3::SimpleWirelessChannel::GetNDevices() const’
   68 |   virtual uint32_t GetNDevices (void) const;
      |                    ^~~~~~~~~~~
In file included from ./ns3/simple-wireless-channel.h:24,
                 from ./ns3/tdma-controller.h:38,
                 from ./ns3/tdma-mac.h:33,
                 from ../src/lifi/model/lifi-user-device-infos.h:5,
                 from ../src/lifi/model/lifi-user-device-infos.cc:1:
./ns3/channel.h:68:23: note: overridden function is ‘virtual std::size_t ns3::Channel::GetNDevices() const’
   68 |   virtual std::size_t GetNDevices (void) const = 0;
      |                       ^~~~~~~~~~~

In file included from ./ns3/tdma-controller.h:38,
                 from ./ns3/tdma-mac.h:33,
                 from ../src/lifi/model/received-data-model.h:5,
                 from ../src/lifi/model/received-data-model.cc:1:
./ns3/simple-wireless-channel.h:68:20: error: conflicting return type specified for ‘virtual uint32_t ns3::SimpleWirelessChannel::GetNDevices() const’
   68 |   virtual uint32_t GetNDevices (void) const;
      |                    ^~~~~~~~~~~
In file included from ./ns3/simple-wireless-channel.h:24,
                 from ./ns3/tdma-controller.h:38,
                 from ./ns3/tdma-mac.h:33,
                 from ../src/lifi/model/received-data-model.h:5,
                 from ../src/lifi/model/received-data-model.cc:1:
./ns3/channel.h:68:23: note: overridden function is ‘virtual std::size_t ns3::Channel::GetNDevices() const’
   68 |   virtual std::size_t GetNDevices (void) const = 0;
      |                       ^~~~~~~~~~~

In file included from ./ns3/tdma-controller.h:38,
                 from ./ns3/tdma-mac.h:33,
                 from ./ns3/mac-resources-tag.h:5,
                 from ../src/lifi/model/mac-resources-tag.cc:1:
./ns3/simple-wireless-channel.h:68:20: error: conflicting return type specified for ‘virtual uint32_t ns3::SimpleWirelessChannel::GetNDevices() const’
   68 |   virtual uint32_t GetNDevices (void) const;
      |                    ^~~~~~~~~~~
In file included from ./ns3/simple-wireless-channel.h:24,
                 from ./ns3/tdma-controller.h:38,
                 from ./ns3/tdma-mac.h:33,
                 from ./ns3/mac-resources-tag.h:5,
                 from ../src/lifi/model/mac-resources-tag.cc:1:
./ns3/channel.h:68:23: note: overridden function is ‘virtual std::size_t ns3::Channel::GetNDevices() const’
   68 |   virtual std::size_t GetNDevices (void) const = 0;
      |                       ^~~~~~~~~~~

In file included from ./ns3/tdma-controller.h:38,
                 from ./ns3/tdma-mac.h:33,
                 from ./ns3/lifi-user-device-infos.h:5,
                 from ./ns3/lifi-net-device.h:28,
                 from ./ns3/lifi-tx-net-device.h:5,
                 from ../src/lifi/model/lifi-mac-low.cc:5:
./ns3/simple-wireless-channel.h:68:20: error: conflicting return type specified for ‘virtual uint32_t ns3::SimpleWirelessChannel::GetNDevices() const’
   68 |   virtual uint32_t GetNDevices (void) const;
      |                    ^~~~~~~~~~~
In file included from ./ns3/simple-channel.h:23,
                 from ../src/lifi/model/lifi-channel.h:4,
                 from ../src/lifi/model/lifi-mac-low.h:9,
                 from ../src/lifi/model/lifi-mac-low.cc:3:
./ns3/channel.h:68:23: note: overridden function is ‘virtual std::size_t ns3::Channel::GetNDevices() const’
   68 |   virtual std::size_t GetNDevices (void) const = 0;
      |                       ^~~~~~~~~~~

In file included from ./ns3/tdma-controller.h:38,
                 from ./ns3/tdma-mac.h:33,
                 from ./ns3/lifi-user-device-infos.h:5,
                 from ../src/lifi/model/lifi-mac-queue.h:9,
                 from ../src/lifi/model/lifi-tx-mac.h:6,
                 from ../src/lifi/model/lifi-regular-mac.h:13,
                 from ../src/lifi/model/lifi-regular-mac.cc:5:
./ns3/simple-wireless-channel.h:68:20: error: conflicting return type specified for ‘virtual uint32_t ns3::SimpleWirelessChannel::GetNDevices() const’
   68 |   virtual uint32_t GetNDevices (void) const;
      |                    ^~~~~~~~~~~
In file included from ./ns3/simple-channel.h:23,
                 from ./ns3/lifi-channel.h:4,
                 from ../src/lifi/model/lifi-regular-mac.h:10,
                 from ../src/lifi/model/lifi-regular-mac.cc:5:
./ns3/channel.h:68:23: note: overridden function is ‘virtual std::size_t ns3::Channel::GetNDevices() const’
   68 |   virtual std::size_t GetNDevices (void) const = 0;
      |                       ^~~~~~~~~~~

In file included from ./ns3/tdma-controller.h:38,
                 from ./ns3/tdma-mac.h:33,
                 from ./ns3/lifi-user-device-infos.h:5,
                 from ./ns3/lifi-net-device.h:28,
                 from ./ns3/lifi-rx-net-device.h:9,
                 from ../src/lifi/model/wifi-ap-net-device.cc:13:
./ns3/simple-wireless-channel.h:68:20: error: conflicting return type specified for ‘virtual uint32_t ns3::SimpleWirelessChannel::GetNDevices() const’
   68 |   virtual uint32_t GetNDevices (void) const;
      |                    ^~~~~~~~~~~
In file included from ./ns3/network-module.h:17,
                 from ./ns3/wifi-ap-net-device.h:9,
                 from ../src/lifi/model/wifi-ap-net-device.cc:1:
./ns3/channel.h:68:23: note: overridden function is ‘virtual std::size_t ns3::Channel::GetNDevices() const’
   68 |   virtual std::size_t GetNDevices (void) const = 0;
      |                       ^~~~~~~~~~~

Waf: Leaving directory `/home/arun/ns-allinone-3.31/ns-3.31/build'
Build failed
 -> task in 'ns3-lifi' failed with exit status 1 (run with -v to display more information)
 -> task in 'ns3-lifi' failed with exit status 1 (run with -v to display more information)
 -> task in 'ns3-lifi' failed with exit status 1 (run with -v to display more information)
 -> task in 'ns3-lifi' failed with exit status 1 (run with -v to display more information)
 -> task in 'ns3-lifi' failed with exit status 1 (run with -v to display more information)
 -> task in 'ns3-lifi' failed with exit status 1 (run with -v to display more information)
Traceback (most recent call last):
  File "./build.py", line 175, in <module>
    sys.exit(main(sys.argv))
  File "./build.py", line 166, in main
    build_ns3(config, build_examples, build_tests, args, build_options)
  File "./build.py", line 86, in build_ns3
    run_command([sys.executable, "waf", "build"] + build_options)
  File "/home/arun/ns-allinone-3.31/util.py", line 25, in run_command
    raise CommandError("Command %r exited with code %i" % (argv, retval))
util.CommandError: Command ['/usr/bin/python3', 'waf', 'build'] exited with code 1

**Comment by shakir01** [comment]
> Dear sir,
> now i getting this following errors, kindly help-me to resolve
> 
> configure' finished successfully (4.449s)
> => /usr/bin/python3 waf build
> Waf: Entering directory `/home/arun/ns-allinone-3.31/ns-3.31/build'
> [1904/2121] Compiling src/lifi/model/wifi-ap-net-device.cc
> [1905/2121] Compiling src/lifi/model/lifi-constant-velocity-mobility-model.cc
> [1906/2121] Compiling src/lifi/model/lifi-user-device-infos.cc
> [1907/2121] Compiling src/lifi/model/received-data-model.cc
> [2047/2121] Compiling src/lifi/model/lifi-mac-low.cc
> [2048/2121] Compiling src/lifi/model/mac-resources-tag.cc
> [2049/2121] Compiling src/lifi/model/lifi-regular-mac.cc
> [2050/2121] Compiling src/lifi/helper/wifi-ap-helper.cc
> In file included from ./ns3/tdma-controller.h:38,
> from ./ns3/tdma-mac.h:33,
> from ../src/lifi/model/lifi-user-device-infos.h:5,
> from ../src/lifi/model/lifi-user-device-infos.cc:1:
> ./ns3/simple-wireless-channel.h:68:20: error: conflicting return type specified for ‘virtual uint32_t ns3::SimpleWirelessChannel::GetNDevices() const’
> 68 | virtual uint32_t GetNDevices (void) const;
> | ^~~~~~~~~~~
> In file included from ./ns3/simple-wireless-channel.h:24,
> from ./ns3/tdma-controller.h:38,
> from ./ns3/tdma-mac.h:33,
> from ../src/lifi/model/lifi-user-device-infos.h:5,
> from ../src/lifi/model/lifi-user-device-infos.cc:1:
> ./ns3/channel.h:68:23: note: overridden function is ‘virtual std::size_t ns3::Channel::GetNDevices() const’
> 68 | virtual std::size_t GetNDevices (void) const = 0;
> | ^~~~~~~~~~~
> 
> In file included from ./ns3/tdma-controller.h:38,
> from ./ns3/tdma-mac.h:33,
> from ../src/lifi/model/received-data-model.h:5,
> from ../src/lifi/model/received-data-model.cc:1:
> ./ns3/simple-wireless-channel.h:68:20: error: conflicting return type specified for ‘virtual uint32_t ns3::SimpleWirelessChannel::GetNDevices() const’
> 68 | virtual uint32_t GetNDevices (void) const;
> | ^~~~~~~~~~~
> In file included from ./ns3/simple-wireless-channel.h:24,
> from ./ns3/tdma-controller.h:38,
> from ./ns3/tdma-mac.h:33,
> from ../src/lifi/model/received-data-model.h:5,
> from ../src/lifi/model/received-data-model.cc:1:
> ./ns3/channel.h:68:23: note: overridden function is ‘virtual std::size_t ns3::Channel::GetNDevices() const’
> 68 | virtual std::size_t GetNDevices (void) const = 0;
> | ^~~~~~~~~~~
> 
> In file included from ./ns3/tdma-controller.h:38,
> from ./ns3/tdma-mac.h:33,
> from ./ns3/mac-resources-tag.h:5,
> from ../src/lifi/model/mac-resources-tag.cc:1:
> ./ns3/simple-wireless-channel.h:68:20: error: conflicting return type specified for ‘virtual uint32_t ns3::SimpleWirelessChannel::GetNDevices() const’
> 68 | virtual uint32_t GetNDevices (void) const;
> | ^~~~~~~~~~~
> In file included from ./ns3/simple-wireless-channel.h:24,
> from ./ns3/tdma-controller.h:38,
> from ./ns3/tdma-mac.h:33,
> from ./ns3/mac-resources-tag.h:5,
> from ../src/lifi/model/mac-resources-tag.cc:1:
> ./ns3/channel.h:68:23: note: overridden function is ‘virtual std::size_t ns3::Channel::GetNDevices() const’
> 68 | virtual std::size_t GetNDevices (void) const = 0;
> | ^~~~~~~~~~~
> 
> In file included from ./ns3/tdma-controller.h:38,
> from ./ns3/tdma-mac.h:33,
> from ./ns3/lifi-user-device-infos.h:5,
> from ./ns3/lifi-net-device.h:28,
> from ./ns3/lifi-tx-net-device.h:5,
> from ../src/lifi/model/lifi-mac-low.cc:5:
> ./ns3/simple-wireless-channel.h:68:20: error: conflicting return type specified for ‘virtual uint32_t ns3::SimpleWirelessChannel::GetNDevices() const’
> 68 | virtual uint32_t GetNDevices (void) const;
> | ^~~~~~~~~~~
> In file included from ./ns3/simple-channel.h:23,
> from ../src/lifi/model/lifi-channel.h:4,
> from ../src/lifi/model/lifi-mac-low.h:9,
> from ../src/lifi/model/lifi-mac-low.cc:3:
> ./ns3/channel.h:68:23: note: overridden function is ‘virtual std::size_t ns3::Channel::GetNDevices() const’
> 68 | virtual std::size_t GetNDevices (void) const = 0;
> | ^~~~~~~~~~~
> 
> In file included from ./ns3/tdma-controller.h:38,
> from ./ns3/tdma-mac.h:33,
> from ./ns3/lifi-user-device-infos.h:5,
> from ../src/lifi/model/lifi-mac-queue.h:9,
> from ../src/lifi/model/lifi-tx-mac.h:6,
> from ../src/lifi/model/lifi-regular-mac.h:13,
> from ../src/lifi/model/lifi-regular-mac.cc:5:
> ./ns3/simple-wireless-channel.h:68:20: error: conflicting return type specified for ‘virtual uint32_t ns3::SimpleWirelessChannel::GetNDevices() const’
> 68 | virtual uint32_t GetNDevices (void) const;
> | ^~~~~~~~~~~
> In file included from ./ns3/simple-channel.h:23,
> from ./ns3/lifi-channel.h:4,
> from ../src/lifi/model/lifi-regular-mac.h:10,
> from ../src/lifi/model/lifi-regular-mac.cc:5:
> ./ns3/channel.h:68:23: note: overridden function is ‘virtual std::size_t ns3::Channel::GetNDevices() const’
> 68 | virtual std::size_t GetNDevices (void) const = 0;
> | ^~~~~~~~~~~
> 
> In file included from ./ns3/tdma-controller.h:38,
> from ./ns3/tdma-mac.h:33,
> from ./ns3/lifi-user-device-infos.h:5,
> from ./ns3/lifi-net-device.h:28,
> from ./ns3/lifi-rx-net-device.h:9,
> from ../src/lifi/model/wifi-ap-net-device.cc:13:
> ./ns3/simple-wireless-channel.h:68:20: error: conflicting return type specified for ‘virtual uint32_t ns3::SimpleWirelessChannel::GetNDevices() const’
> 68 | virtual uint32_t GetNDevices (void) const;
> | ^~~~~~~~~~~
> In file included from ./ns3/network-module.h:17,
> from ./ns3/wifi-ap-net-device.h:9,
> from ../src/lifi/model/wifi-ap-net-device.cc:1:
> ./ns3/channel.h:68:23: note: overridden function is ‘virtual std::size_t ns3::Channel::GetNDevices() const’
> 68 | virtual std::size_t GetNDevices (void) const = 0;
> | ^~~~~~~~~~~
> 
> Waf: Leaving directory `/home/arun/ns-allinone-3.31/ns-3.31/build'
> Build failed
> -> task in 'ns3-lifi' failed with exit status 1 (run with -v to display more information)
> -> task in 'ns3-lifi' failed with exit status 1 (run with -v to display more information)
> -> task in 'ns3-lifi' failed with exit status 1 (run with -v to display more information)
> -> task in 'ns3-lifi' failed with exit status 1 (run with -v to display more information)
> -> task in 'ns3-lifi' failed with exit status 1 (run with -v to display more information)
> -> task in 'ns3-lifi' failed with exit status 1 (run with -v to display more information)
> Traceback (most recent call last):
> File "./build.py", line 175, in
> sys.exit(main(sys.argv))
> File "./build.py", line 166, in main
> build_ns3(config, build_examples, build_tests, args, build_options)
> File "./build.py", line 86, in build_ns3
> run_command([sys.executable, "waf", "build"] + build_options)
> File "/home/arun/ns-allinone-3.31/util.py", line 25, in run_command
> raise CommandError("Command %r exited with code %i" % (argv, retval))
> util.CommandError: Command ['/usr/bin/python3', 'waf', 'build'] exited with code 1

Sorry for the late response.
I am looking for your issue and will update you soon.
Regards

**Comment by runa988** [comment]
Ok sir, I be waiting for the better solution

**Comment by runa988** [comment]
sir, good morning. is there any updates regarding previous issue

**Comment by shakir01** [comment]
Can you reach out To me on the following email
***@***.***

**Comment by shakir01** [comment]
> sir, good morning. is there any updates regarding previous issue

I had looked at your issue again. it seems that you are mixing my previous uploaded files with the current. Kindly delete the previous framework and download the latest from git. If the issue still persists contact me on email: shakir702@yahoo.com
